#each route describes how an incoming url will be process by platform.sh.
"https://{default}":
  type: upstream
  upstream: "ll_projects"
"https://www.{default}/":
  type: redirect
  to: "https://{default}/"
#each service listed will be diployed in its own container as part of your
#.paltform.sh project.
db:
  type: postgresql:12
  disk: 1024


